#!/usr/bin/env python3
from pathlib import Path
import argparse


def extract_field(lines, prefix):
	return [line.replace(prefix, '') for line in lines if line.startswith(prefix)][0]

def remove_field(lines, prefix):
	return [line for line in lines if not line.startswith(prefix)]


# Parse our command-line arguments
parser = argparse.ArgumentParser()
parser.add_argument('shortcut', type=Path, help='Path to the .desktop file generated by Wine that points to a Windows shortcut file')
args = parser.parse_args()

# Parse the desktop file and remove the existing `Exec=` line
lines = args.shortcut.read_text('utf-8').splitlines()
lines = remove_field(lines, 'Exec=')

# Extract the path to the executable file
directory = extract_field(lines, 'Path=')
executable = extract_field(lines, 'StartupWMClass=')
reconstructed = Path(directory) / executable

# Remove the existing `Path=` line, since it will point to a path that doesn't exist on the host filesystem
# (If we don't do this then the desktop file will fail to launch once it's been exported by Distrobox)
lines = remove_field(lines, 'Path=')

# Generate a new `Exec=` line that runs the executable with our DPI scaling wrapper script, and write the lines back to the desktop file
lines.append(f"Exec=wine-wrapper.py '{reconstructed}'")
args.shortcut.write_text('\n'.join(lines), 'utf-8')
